name: 🚨 Security Vulnerability Report
description: Report a security vulnerability in the Roblox Studio MCP Server
title: "[SECURITY] "
labels: ["security", "vulnerability", "urgent"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 Security Vulnerability Report
        
        **⚠️ IMPORTANT**: This issue template is for reporting security vulnerabilities. 
        
        For general security questions or discussions, please use the regular issue template.
        
        **🔒 Please DO NOT** include sensitive information, proof-of-concept code, or exploit details in this issue.
        
        **📧 For highly sensitive vulnerabilities**, consider emailing security details privately instead.

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the security vulnerability
      placeholder: Describe the security issue without including sensitive details...
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected by this vulnerability?
      placeholder: |
        - Version 0.1.x
        - Version 0.2.x
        - All versions
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced? (Do not include exploit code)
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: What is the severity of this vulnerability?
      options:
        - Critical (Remote Code Execution, Data Breach)
        - High (Privilege Escalation, Authentication Bypass)
        - Medium (Information Disclosure, Denial of Service)
        - Low (Minor security issues)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker achieve with this vulnerability?
      placeholder: Describe the potential impact without providing exploit details...
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Do you have any suggestions for fixing this vulnerability?
      placeholder: Optional: Describe how this vulnerability could be fixed...

  - type: checkboxes
    id: disclosure-preference
    attributes:
      label: Disclosure Preference
      description: How would you like this vulnerability to be disclosed?
      options:
        - label: I agree to coordinated disclosure (recommended)
          required: false
        - label: I prefer immediate public disclosure
          required: false
        - label: I would like to discuss disclosure timeline privately
          required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information that might be helpful?
      placeholder: References, related issues, etc...

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this report, you agree to the following
      options:
        - label: I have read and agree to the [Security Policy](SECURITY.md)
          required: true
        - label: I understand that this is a public repository and my report will be visible to others
          required: true
        - label: I will not use this vulnerability for malicious purposes
          required: true
